version: '3'

services:
  app:
    build: 
      dockerfile: ./Dockerfile
      context: ./
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: none
    container_name: test
    environment:
      TIMES: "15"
      URL:  "www.uol.com.br"
